# httpd
- name: httpd is installed
  yum : pkg=httpd state=installed
  tags: httpd

- name: httpd is running and enabled
  service: name=httpd state=running enabled=yes
  tags: httpd

# php
- name: php is instaled
  yum: pkg={{item}} state=installed
  with_items:
    - php
    - php-mbstring
    - php-mysql
  notify:
    - restart httpd
  tags: httpd

- name: php is configured
  notify:
    - restart httpd
  lineinfile: dest="/etc/php.ini" state=present regexp="^\;date.timezone =$" line="date.timezone = Asia/Tokyo" backrefs=yes
  tags: httpd

# wordpress
- name: unzip installed
  yum : name=unzip state=latest
  tags: wordpress

- name: wordpress source files deployed
  unarchive: src="wordpress-4.2.4-ja.zip" dest="/var/www/html" owner=apache group=apache mode=0755
  args:
    creates: /var/www/html/wordpress
  tags: wordpress

- name: wordpress is configured
  template: src="wp-config.php.j2" dest="/var/www/html/wordpress/wp-config.php" owner=apache group=apache mode=0644
  tags: wordpress

- name: apache is wordpress directory owner
  file: path=/var/www/html/wordpress owner=apache group=apache recurse=yes
  tags: wordpress

